include ../Defs.inc

SOURCESCPP = Array1d_double64.cpp \
             Cluster.cpp \
             Matrix.cpp \
             Mesh.cpp \
             Data.cpp \
             Driver.cpp \
             Options.cpp \
			 Solver.cpp

include ../Make.inc

clean:
	-rm *.o
