DIRECTORY  = src
SOURCESCPP = htfeti.cpp
# PardisoSolver.cpp 

#LIBDEP     = -L../../lib -lAlgebra -lSplitters -lUtilities -lCompiler -lBlock_tridiag_matrix_s -lModules_s -lFeti_Abort_s $(SHARED_BLAS) $(SHARED_INTEL)
include ../Defs.inc
include ../Make.inc
